version: '2'
services:
  postgres-0:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Informatica26?
  spring-0:
    image: spring_image
    ports:
      - 8080:8080
    depends_on:
      - postgres-0
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres-0:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=Informatica26?
  angular-0:
    image: angular_image
    ports:
      - 4200:4200




